// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNpBiTSmv9KhBTPsQKCM_QB6Lifc3bTmE',
    appId: '1:386436101872:web:caa019bd76be53f669f435',
    messagingSenderId: '386436101872',
    projectId: 'siap-67096',
    authDomain: 'siap-67096.firebaseapp.com',
    storageBucket: 'siap-67096.appspot.com',
    measurementId: 'G-K4LH1GJZFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD_387AcBfiwONI3Y5ijWxfK_ClVvyN6w',
    appId: '1:386436101872:android:11fe356a505092d069f435',
    messagingSenderId: '386436101872',
    projectId: 'siap-67096',
    storageBucket: 'siap-67096.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7RqE3Qi5M-hfxuwmDLC7e6CkB0r5LCEc',
    appId: '1:386436101872:ios:4494e867af806a7969f435',
    messagingSenderId: '386436101872',
    projectId: 'siap-67096',
    storageBucket: 'siap-67096.appspot.com',
    iosBundleId: 'com.rha.siap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7RqE3Qi5M-hfxuwmDLC7e6CkB0r5LCEc',
    appId: '1:386436101872:ios:4494e867af806a7969f435',
    messagingSenderId: '386436101872',
    projectId: 'siap-67096',
    storageBucket: 'siap-67096.appspot.com',
    iosBundleId: 'com.rha.siap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNpBiTSmv9KhBTPsQKCM_QB6Lifc3bTmE',
    appId: '1:386436101872:web:9bee9af8963091f069f435',
    messagingSenderId: '386436101872',
    projectId: 'siap-67096',
    authDomain: 'siap-67096.firebaseapp.com',
    storageBucket: 'siap-67096.appspot.com',
    measurementId: 'G-W0N61HX092',
  );
}
